#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_TYPE_DELAY 40  // wait 40 ms after ctrl-shit-u in linux
#define UNICODE_CYCLE_PERSIST false
