#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 1
#define RGBLIGHT_DEFAULT_SPD 2

//#define RGBLIGHT_LAYERS
//#define RGBLIGHT_LAYER_BLINK

//#ifdef UNICODE_ENABLE
//#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS
//#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
//#define UNICODE_TYPE_DELAY 40  // wait 40 ms after ctrl-shit-u in linux
//#define UNICODE_CYCLE_PERSIST false
//#endif